### ISSUE TITLE
No Dremel printer available in printers list

### ISSUE THREAD

**Issue by polybius80** [timmehtimmeh/Cura-Dremel-3D20-Plugin#77]
Hi I installed your plug-in in various cura versions but the dremel printer is not listed, I tested many versions of cura and your last 2 versions of the plug-in and also installed manually in each case and restarted cura many times, there is the menu of the plug in, its installed but still not printer in the list

I am using the latest ubuntu (21.04) as reference 

thank you for your time

**Comment by timmehtimmeh** [comment]
Hi @polybius80 

I just tested using Ubuntu 20.10 following steps outlined below and was able to add a Dremel 3D20 from a clean install of Cura.

**Steps**
1)  Download [Ultimaker Cura 4.9.1 AppImage](https://software.ultimaker.com/cura/4.9_20210511_Ultimaker_Cura-4.9.1.AppImage)
2) Moved the .appimage to my Desktop and ran `chmod 755` on the Appimage
3)  Reset Cura to the factory state by deleting cura's caches (done by running the following commands):
```
rm -rf ~/.local/share/cura/*
rm -rf ~/.config/cura/* 
rm -rf ~/.cache/cura/*
```
3. Launch Cura & stepped through the initial prompts.  When it came time to choose a printer you can see that the Dremel 3D20 wasn't an option.  I simply selected the Ultimaker S5 default option
![Cura-No-Dremel](https://user-images.githubusercontent.com/19733103/122273007-d42b7980-ce95-11eb-9c33-c71fb3194bde.png)

4. Open up Cura's marketplace (note that because I deleted Cura's caches I have no plugins installed.
![Screenshot from 2021-06-16 11-08-33](https://user-images.githubusercontent.com/19733103/122273291-1fde2300-ce96-11eb-8d47-f72c3c9caea1.png)

5. Navigate to the Marketplace's plugins directory, find the Dremel 3D20 plugin (ver 0.6.4) and click the Install Button
![Install](https://user-images.githubusercontent.com/19733103/122273427-48661d00-ce96-11eb-99a2-bc96c3d645e8.png)

6. At this point I was prompted to restart Cura, so I clicked the "Quit Ultimaker Cura" button
![Restart](https://user-images.githubusercontent.com/19733103/122273473-51ef8500-ce96-11eb-9832-2549ef87a962.png)

7. I then re-launched the Appimage, navigated to `Settings->Printer->Add Printer`
![AddPrinter](https://user-images.githubusercontent.com/19733103/122273590-7186ad80-ce96-11eb-8769-ad2e7eeef928.png)

8. Scrolling down the Dremel printer is now an option.
![AddDremel](https://user-images.githubusercontent.com/19733103/122273661-8bc08b80-ce96-11eb-9cf3-f705c0409639.png)

9. The Dremel3D20 was successfully added:
![DremelAdded](https://user-images.githubusercontent.com/19733103/122276773-fcb57280-ce99-11eb-8a88-c95309308075.jpg)


Please try the above sequence...if following those steps don't work then if you don't mind uploading your cura.log file located in
`~/.local/share/cura/4.9/cura.log` after performing the steps above it would be helpful.   Additionally if the above sequence doesn't work please let me know if you see a Dremel3D20.def.json in `~/.local/share/cura/4.9/definitions/Dremel3D20.def.json`

Internally the plugin contains a zip file that it unzips to put the printer definition, material definition, and settings into the proper location.  Every time that cura starts, the plugin checks whether all the necessary files are installed and if they are the correct version. If not then the [plugin unzips the correct version from the zip file and copies the files to their correct location](https://github.com/timmehtimmeh/Cura-Dremel-3D20-Plugin/blob/6ade070d48460260e85ffcf7eae3877376643845/plugins/Dremel3D20/Dremel3D20.py#L258-L304).  It may be that on your computer for some reason some part of that process isn't working (maybe a permissions error, maybe something else...)

**Comment by timmehtimmeh** [comment]
One additional note for what it's worth: I just upgraded my computer to Ubuntu 21.04 and followed the above steps again (once again clearing cura's cache first to start cura from default settings) and was also able to successfully install the 3D20.

**Comment by polybius80** [comment]
it now works, thank you

apparently it was something with the cura cache

**Comment by timmehtimmeh** [comment]
Awesome - glad to hear that it's working now.   :partying_face:  

If you'd ever used a **really old** version of the plugin and toggled the the plugin's preferences page->install plugin files checkbox that _may_ have caused the issue, I'll review the code to see if there's a chance for improvement in it.

Cheers!
