### ISSUE TITLE
"There are no file formats available to write with"

### ISSUE THREAD

**Issue by edgecase963** [timmehtimmeh/Cura-Dremel-3D20-Plugin#91]
I am currently using a Dremel 3D20 printer on Ultimaker version 5.1.0 (Linux Ubuntu).

It seems to load files, modify the models and slice them just fine. However, when I click the "Save to Removable" button to export the model, I get the error message "There are no file formats available to write with"

I've tried manually exporting it by going to File > Export, but it doesn't even give me the  ".g3drem" file format option.

**Comment by timmehtimmeh** [comment]
@edgecase963 - thanks for the report.  It sounds like the plugin isn't being detected by Cura.  Does the plugin show up in the extensions menu?
![image](https://user-images.githubusercontent.com/19733103/181783246-0185ca13-4d58-4099-9cc0-3958dc1e22ff.png)  

If so please validate that the plugin is version 0.8.0, as prior versions are incompatible with Cura version 5.x

If it doesn't appear in the extensions menu then the plugin isn't installed.  If you recently updated to cura 5.x and haven't reinstalled the plugin you will need to install the plugin again.   Simply go to the cura marketplace and install it again.

I'll test the latest version of cura with ubuntu later tonight, or sometime this weekend.  If the plugin is currently installed, then it would be helpful if you could please send your cura.log, which can be found in:  ```$HOME/.local/share/cura/<Cura version>/cura.log```

**Comment by timmehtimmeh** [comment]
@edgecase963 

I've run the following tests using Ubuntu 20.04.4 LTS:

1. First I wanted to simulate what would happen if a user was running Cura version 4.13 with Dremel Printer Plugin version 0.7.2 and then downloaded/ran Cura version 5.1.0.  The first thing that happens when a user launches Cura version 5.X is that they are presented with a message stating that the plugin can't be loaded (due to Ultimaker making breaking changes that required all plugins to update)
![5 1 0_before_update](https://user-images.githubusercontent.com/19733103/181810822-cab1a446-95fa-42a7-b9dd-3151b3838036.png)

It's worth noting that at this step the printer plugin wasn't listed under the "extensions" menu.

2. From there I went to the marketplace and clicked on the gear icon (with the red notification on it) and clicked the "update" button on the dremel printer plugin.
![Update](https://user-images.githubusercontent.com/19733103/181810999-11a692fa-9638-407e-b4d7-2a5cfa80ca9f.png)

3.  I then restarted cura, loaded benchy, sliced it and clicked "save to removable drive" and the file was successfully saved.
![5 10_works](https://user-images.githubusercontent.com/19733103/181811545-2475bcae-02c6-4a25-86e5-f31a0cbf0fb4.png)

4.  Additionally Selecting `File->Export` has the option to export g3drem files
![export_g3drem](https://user-images.githubusercontent.com/19733103/181811631-549445c2-b648-47bc-9f24-9561276208ec.png)

Please keep me posted with what you find.

Cheers
Tim

**Comment by edgecase963** [comment]
At first, the plugin wasn't showing up in the Extensions drop down menu.

Oddly enough, updating the Dremel extension uninstalled it. Must have been a glitch because when I reinstalled it, *it worked!*
I am indeed using version 0.8.0 now and I'm able to save files in the .g3drem format.
Thank you for your help!

**Comment by timmehtimmeh** [comment]
Glad that it was an easy fix! 🥳 

Cheers
